---
- name: restart nginx
  command: sudo nginx -p /apps/nginx -c nginx.conf -s restart

- name: validate nginx configuration
  command: nginx -t -c /apps/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  command: sudo nginx -p /apps/nginx -c nginx.conf -s reload
